# Generated by Django 5.0.6 on 2024-08-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cartitem_total_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='isOrder',
            field=models.BooleanField(default=False),
        ),
    ]
